/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.forms;

import domain.Dobavljac;
import java.awt.Component;
import ui.panels.PanelMojiProizvodi;
import ui.panels.PanelRoba;

/**
 *
 * @author cid
 */
public class MainForm extends javax.swing.JFrame {
    Component currentPageContent;
    Dobavljac dobavljac;
    /**
     * Creates new form mainForm
     */
    public MainForm(Dobavljac dobavljac) {
        initComponents();
        setLocationRelativeTo(null);
        this.dobavljac = dobavljac; 
//        panelSvaRoba2
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBanner = new javax.swing.JPanel();
        PanelLogOut = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        PanelButtons = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        PanelPage = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 366));
        setPreferredSize(new java.awt.Dimension(1080, 549));

        PanelBanner.setBackground(new java.awt.Color(209, 187, 158));
        PanelBanner.setLayout(new java.awt.BorderLayout());

        PanelLogOut.setBackground(new java.awt.Color(167, 146, 119));
        PanelLogOut.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        jButton1.setBackground(new java.awt.Color(209, 187, 158));
        jButton1.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(84, 51, 16));
        jButton1.setText("Log out");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 187, 158)));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMaximumSize(new java.awt.Dimension(110, 30));
        jButton1.setMinimumSize(new java.awt.Dimension(110, 30));
        jButton1.setPreferredSize(new java.awt.Dimension(130, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PanelLogOut.add(jButton1);

        PanelBanner.add(PanelLogOut, java.awt.BorderLayout.LINE_END);

        PanelButtons.setBackground(new java.awt.Color(167, 146, 119));
        PanelButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        jButton2.setBackground(new java.awt.Color(209, 187, 158));
        jButton2.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(84, 51, 16));
        jButton2.setText("Svi proizvodi");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 187, 158)));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setMaximumSize(new java.awt.Dimension(110, 30));
        jButton2.setMinimumSize(new java.awt.Dimension(110, 30));
        jButton2.setPreferredSize(new java.awt.Dimension(130, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        PanelButtons.add(jButton2);

        jButton3.setBackground(new java.awt.Color(209, 187, 158));
        jButton3.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(84, 51, 16));
        jButton3.setText("Racuni");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 187, 158)));
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setMaximumSize(new java.awt.Dimension(110, 30));
        jButton3.setMinimumSize(new java.awt.Dimension(110, 30));
        jButton3.setPreferredSize(new java.awt.Dimension(130, 30));
        PanelButtons.add(jButton3);

        jButton4.setBackground(new java.awt.Color(209, 187, 158));
        jButton4.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(84, 51, 16));
        jButton4.setText("Moji proizvodi");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 187, 158)));
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setMaximumSize(new java.awt.Dimension(110, 30));
        jButton4.setMinimumSize(new java.awt.Dimension(110, 30));
        jButton4.setPreferredSize(new java.awt.Dimension(130, 30));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        PanelButtons.add(jButton4);

        jButton5.setBackground(new java.awt.Color(209, 187, 158));
        jButton5.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(84, 51, 16));
        jButton5.setText("Nalog");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 187, 158)));
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setMaximumSize(new java.awt.Dimension(110, 30));
        jButton5.setMinimumSize(new java.awt.Dimension(110, 30));
        jButton5.setPreferredSize(new java.awt.Dimension(130, 30));
        PanelButtons.add(jButton5);

        PanelBanner.add(PanelButtons, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelBanner, java.awt.BorderLayout.PAGE_START);

        PanelPage.setBackground(new java.awt.Color(234, 216, 192));
        PanelPage.setLayout(new java.awt.BorderLayout());
        getContentPane().add(PanelPage, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (currentPageContent!=null) PanelPage.remove(currentPageContent);
        currentPageContent = new PanelRoba();
        PanelPage.add(currentPageContent);
        PanelPage.updateUI();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (currentPageContent!=null) PanelPage.remove(currentPageContent);
        currentPageContent = new PanelMojiProizvodi(dobavljac);
        PanelPage.add(currentPageContent);
        PanelPage.updateUI();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm(new Dobavljac()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBanner;
    private javax.swing.JPanel PanelButtons;
    private javax.swing.JPanel PanelLogOut;
    private javax.swing.JPanel PanelPage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
}
