/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui.forms;

import controller.Controller;
import domain.Dobavljac;
import javax.swing.JOptionPane;

/**
 *
 * @author cid
 */
public class RegisterForm extends javax.swing.JDialog {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        PibTextField = new javax.swing.JTextField();
        NazivTextFlied = new javax.swing.JTextField();
        EmailTextFlied = new javax.swing.JTextField();
        RegisterButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        RacunlTextFlied = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ErrorMessageLabel = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 242, 225));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 242, 225));
        jPanel1.setForeground(new java.awt.Color(84, 51, 16));

        jLabel6.setForeground(new java.awt.Color(84, 51, 16));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("PIB:");

        jLabel7.setForeground(new java.awt.Color(84, 51, 16));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Naziv:");

        jLabel8.setForeground(new java.awt.Color(84, 51, 16));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Email:");

        jLabel9.setForeground(new java.awt.Color(84, 51, 16));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Lozinka:");

        jLabel10.setForeground(new java.awt.Color(84, 51, 16));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Ponovite lozinku:");

        PibTextField.setBackground(new java.awt.Color(167, 146, 119));
        PibTextField.setForeground(new java.awt.Color(84, 51, 16));
        PibTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PibTextFieldActionPerformed(evt);
            }
        });

        NazivTextFlied.setBackground(new java.awt.Color(167, 146, 119));
        NazivTextFlied.setForeground(new java.awt.Color(84, 51, 16));

        EmailTextFlied.setBackground(new java.awt.Color(167, 146, 119));
        EmailTextFlied.setForeground(new java.awt.Color(84, 51, 16));

        RegisterButton.setBackground(new java.awt.Color(209, 187, 158));
        RegisterButton.setForeground(new java.awt.Color(84, 51, 16));
        RegisterButton.setText("Register");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(209, 187, 158));
        jButton2.setForeground(new java.awt.Color(84, 51, 16));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        RacunlTextFlied.setBackground(new java.awt.Color(167, 146, 119));
        RacunlTextFlied.setForeground(new java.awt.Color(84, 51, 16));

        jLabel11.setForeground(new java.awt.Color(84, 51, 16));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Broj racuna:");

        ErrorMessageLabel.setForeground(new java.awt.Color(102, 0, 0));
        ErrorMessageLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ErrorMessageLabel.setText("   ");

        jPasswordField1.setBackground(new java.awt.Color(167, 146, 119));
        jPasswordField1.setForeground(new java.awt.Color(84, 51, 16));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jPasswordField2.setBackground(new java.awt.Color(167, 146, 119));
        jPasswordField2.setForeground(new java.awt.Color(84, 51, 16));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(RegisterButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PibTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(NazivTextFlied)
                            .addComponent(EmailTextFlied)
                            .addComponent(RacunlTextFlied)
                            .addComponent(jPasswordField1)
                            .addComponent(jPasswordField2)))
                    .addComponent(ErrorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(PibTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(NazivTextFlied, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(EmailTextFlied, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RacunlTextFlied, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorMessageLabel)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterButton)
                    .addComponent(jButton2))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        Integer pib = 0;
        try {
            pib = PibTextField.getText().equals("") ? 0 : Integer.parseInt(PibTextField.getText());
        } catch (NumberFormatException e) {
            ErrorMessageLabel.setText("PIB mora biti 9 cifara");
            return;
        }
        String naziv = NazivTextFlied.getText().strip();
        String email = EmailTextFlied.getText().strip();
        String brojRacuna = RacunlTextFlied.getText().strip();
        String lozinka = String.copyValueOf(jPasswordField1.getPassword());
        String ponovnaLozinka = String.copyValueOf(jPasswordField2.getPassword());
        if (validirajUnos(pib, naziv, email, brojRacuna, lozinka, ponovnaLozinka)) {
            Dobavljac novi = new Dobavljac(pib, naziv, email, lozinka, brojRacuna);
            if (Controller.getInstance().registerDobavljac(novi)) {
                this.dispose();
                return;
            }
            JOptionPane.showMessageDialog(this, "Greska pri registraciji pokusajte ponovo.", "GRESKA", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void PibTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PibTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PibTextFieldActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegisterForm dialog = new RegisterForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailTextFlied;
    private javax.swing.JLabel ErrorMessageLabel;
    private javax.swing.JTextField NazivTextFlied;
    private javax.swing.JTextField PibTextField;
    private javax.swing.JTextField RacunlTextFlied;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    // End of variables declaration//GEN-END:variables

    private boolean validirajUnos(Integer pib, String naziv, String email, String brojRacuna, String lozinka, String ponovnaLozinka) {
        if ( (pib+"").length() != 9) {
            ErrorMessageLabel.setText("PIB mora biti 9 cifara");
            return false;
        }
        if (naziv==null || naziv.length() < 2) {
            ErrorMessageLabel.setText("Naziv mora biti bar 2 karaktera");
            return false;
        }
        if (email==null || !email.contains("@") || !email.endsWith(".com")) {
            ErrorMessageLabel.setText("Email mora biti validan");
            return false;
        }
        if (brojRacuna==null || brojRacuna.length()<9 || brojRacuna.charAt(3)!='-' || brojRacuna.charAt(brojRacuna.length()-4)!='-')  {
            ErrorMessageLabel.setText("Broj racuna mora biti validan");
            return false;
        }
        if (lozinka==null || lozinka.length() < 8) {
            ErrorMessageLabel.setText("Lozinka mora da ima bar 8 karaktera");
            return false;
        }
        if (ponovnaLozinka==null || !ponovnaLozinka.equals(lozinka)) {
            ErrorMessageLabel.setText("Loiznke se ne poklapaju");
            return false;
        }
        ErrorMessageLabel.setText("   ");
        return true;
    }
}
