/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.panels;

import domain.Roba;

/**
 *
 * @author cid
 */
public class PanelProizvod extends javax.swing.JPanel {

    /**
     * Creates new form PanelProizvod
     */
    public PanelProizvod() {
        initComponents();
    }
    
    public PanelProizvod(Roba r) {
        initComponents();
        LabelIme.setText(r.getNaziv());
        LabelOpis.setText(r.getOpis());
        LabelCena.setText(""+r.getCena());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelIme = new javax.swing.JLabel();
        LabelOpis = new javax.swing.JLabel();
        LabelCena = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 242, 225));
        setMaximumSize(new java.awt.Dimension(37000, 200));
        setMinimumSize(new java.awt.Dimension(600, 150));
        setPreferredSize(new java.awt.Dimension(600, 150));
        setLayout(new java.awt.BorderLayout());

        LabelIme.setFont(new java.awt.Font("DejaVu Serif Condensed", 0, 14)); // NOI18N
        LabelIme.setForeground(new java.awt.Color(84, 51, 16));
        LabelIme.setText("[ImeProizvoda]");
        LabelIme.setMaximumSize(new java.awt.Dimension(98, 25));
        LabelIme.setMinimumSize(new java.awt.Dimension(98, 25));
        LabelIme.setPreferredSize(new java.awt.Dimension(98, 25));
        add(LabelIme, java.awt.BorderLayout.PAGE_START);

        LabelOpis.setFont(new java.awt.Font("DejaVu Serif Condensed", 0, 14)); // NOI18N
        LabelOpis.setForeground(new java.awt.Color(84, 51, 16));
        LabelOpis.setText("[OpisProizovda]");
        add(LabelOpis, java.awt.BorderLayout.CENTER);

        LabelCena.setFont(new java.awt.Font("DejaVu Serif Condensed", 0, 14)); // NOI18N
        LabelCena.setForeground(new java.awt.Color(84, 51, 16));
        LabelCena.setText("[CenaProizvoda]");
        add(LabelCena, java.awt.BorderLayout.LINE_END);

        jSeparator1.setBackground(new java.awt.Color(234, 216, 192));
        jSeparator1.setForeground(new java.awt.Color(255, 242, 225));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 15));
        add(jSeparator1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCena;
    private javax.swing.JLabel LabelIme;
    private javax.swing.JLabel LabelOpis;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
