/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.panels;

import controller.Controller;
import domain.Dobavljac;
import domain.Roba;
import java.awt.event.ContainerEvent;
import java.awt.event.ContainerListener;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author cid
 */
public class PanelMojiProizvodi extends javax.swing.JPanel {
    Controller controller;
    DefaultTableModel dtm;
    Dobavljac dobavljac;
    LinkedList<Roba> robaDobavljaca = new LinkedList<>();
    /**
     * Creates new form PanelMojiProizvodi
     */
    public PanelMojiProizvodi(Dobavljac dobavljac) {
        initComponents();
        
        controller = Controller.getInstance();
        this.dobavljac = dobavljac;
        initTable();
        jTable1.addContainerListener(new ContainerListener() {
            @Override
            public void componentAdded(ContainerEvent ce) {
//                (javax.swing.JTable)ce.getContainer())
            }

            @Override
            public void componentRemoved(ContainerEvent ce) {
                int red = ((javax.swing.JTable)ce.getContainer()).getEditingRow();
//                dtm.getValueAt(red, indekskolone)
                System.out.println(red);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        PretragaTextField = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setBackground(new java.awt.Color(234, 216, 192));
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(234, 216, 192));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 102, 102));

        jTable1.setBackground(new java.awt.Color(234, 216, 192));
        jTable1.setForeground(new java.awt.Color(84, 51, 16));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Naziv", "Opis", "Dostupna Kolicina", "Cena"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(234, 216, 192));
        jPanel1.setMinimumSize(new java.awt.Dimension(620, 40));
        jPanel1.setPreferredSize(new java.awt.Dimension(620, 40));

        PretragaTextField.setBackground(new java.awt.Color(167, 146, 119));
        PretragaTextField.setForeground(new java.awt.Color(84, 51, 16));
        PretragaTextField.setMinimumSize(new java.awt.Dimension(140, 25));
        PretragaTextField.setPreferredSize(new java.awt.Dimension(140, 25));
        PretragaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PretragaTextFieldActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(209, 187, 158));
        jButton5.setForeground(new java.awt.Color(84, 51, 16));
        jButton5.setText("Pretrazi");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(209, 187, 158));
        jButton6.setForeground(new java.awt.Color(84, 51, 16));
        jButton6.setText("Obrisi");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(209, 187, 158));
        jButton7.setForeground(new java.awt.Color(84, 51, 16));
        jButton7.setText("Nova Roba");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(209, 187, 158));
        jButton8.setForeground(new java.awt.Color(84, 51, 16));
        jButton8.setText("Primeni izmene");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(PretragaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PretragaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void PretragaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PretragaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PretragaTextFieldActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String token = PretragaTextField.getText().strip().toLowerCase();
        dtm.setRowCount(0);
        for(Roba r : robaDobavljaca) {
          if (r.getNaziv().toLowerCase().contains(token))
            dtm.addRow(new Object[]{ r.getIdRoba(), r.getNaziv(), r.getOpis(), r.getDostupnaKolicina(), r.getCena()});
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int[] redovi = jTable1.getSelectedRows();
        LinkedList<Long> listId = new LinkedList<>();
        for (int red : redovi)
            listId.add( (Long) jTable1.getValueAt(red, 0) );
        int affected = controller.deleteRoba(listId);
        if (affected==1)
            JOptionPane.showMessageDialog(this, "Uspesno obrisana roba.");
        else if (affected > 1) JOptionPane.showMessageDialog(this, "Uspesno obrisano "+affected+" roba.");
        initTable();
        
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PretragaTextField;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void initTable() {
        Controller controller = Controller.getInstance();
        LinkedList<Roba> robe = controller.getRobaForDobavljac(dobavljac.getIdDobavljac());
        TableModel tm = jTable1.getModel();
        dtm = (DefaultTableModel) tm;
        dtm.setRowCount(0);
        for(Roba r : robe) {
          dtm.addRow(new Object[]{ r.getIdRoba(), r.getNaziv(), r.getOpis(), r.getDostupnaKolicina(), r.getCena()});
          robaDobavljaca.add(r);
        }
    }
}
